# Site settings
title: Cevi Herdian
email: itsmecevi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Cevi Herdian website.

# url of domain
url: itsmecevi.github.io
# baseurl: /path/to/blog (leave this empty for user page)
baseurl: 

# User setting
owner: Cevi Herdian
email: "itsmecevi [at] gmail [dot] com"
github_username: itsmecevi
linkedin_username: Cevi Herdian
address:
  - line: Berlin  
copyright: "Cevi Herdian"

# API settings
google_api_key:

# Build settings
markdown: kramdown
highlighter: rouge
