# Site settings
title: Gertaone
email: gertaone@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Gertaone Website.

# url of domain
url: gertaone.github.io
# baseurl: /path/to/blog (leave this empty for user page)
baseurl: 

# User setting
owner: Cevi Herdian
email: "gertaone [at] gmail [dot] com"
github_username: gertaone
linkedin_username: Cevi Herdian
address:
  - line: Berlin  
copyright: "Gertaone"

# API settings
google_api_key:

# Build settings
markdown: kramdown
highlighter: rouge
